apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rustdesk.fullname" . }}-hbbs-pvc
  labels:
    {{- include "rustdesk.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rustdesk.fullname" . }}-hbbr-pvc
  labels:
    {{- include "rustdesk.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}