apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ipinfo.fullname" . }}-config
  labels:
    {{- include "ipinfo.labels" . | nindent 4 }}
data:
{{- range $filename, $content := .Values.nginxConfigs }}
  {{ $filename }}: |
{{ $content | nindent 4 }}
{{- end }}
